title: ezec
description: Web application to manage peer evaluation extra credit in ICS 311 at the University of Hawaii at Manoa.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
